name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, python-version: '3.8'}
          - {os: ubuntu-latest, python-version: '3.13'}
          - {os: windows-latest, python-version: '3.8'}
          - {os: windows-latest, python-version: '3.13'}
          # 3.8 is not supported on macos-arm64, just support 3.13 there
          - {os: macos-latest, python-version: '3.13'}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -e .
      - run: python -m tests

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -e . -r docs/requirements.txt
      - run: sphinx-build -W -b html docs docs/_build/html
